'use strict';

const COLLECTION_ROLES = (process.env.BASE_COLLECTION_ROLES || 'saas_roles').trim();
const COLLECTION_USERS = (process.env.BASE_COLLECTION_USERS || 'saas_users').trim();
const COLLECTION_DEPARTAMENTOS = (process.env.BASE_COLLECTION_DEPARTAMENTOS || 'departamentos').trim();
const COLLECTION_PUESTOS = (process.env.BASE_COLLECTION_PUESTOS || 'puestos').trim();
const COLLECTION_EMPLEADOS = (process.env.BASE_COLLECTION_EMPLEADOS || 'empleados').trim();
const COLLECTION_TURNOS = (process.env.BASE_COLLECTION_TURNOS || 'turnos').trim();
const COLLECTION_ATTENDANCE_RECORDS = (process.env.BASE_COLLECTION_ATTENDANCE_RECORDS || 'attendance_records').trim();
const COLLECTION_DAILY_ATTENDANCE = (process.env.BASE_COLLECTION_DAILY_ATTENDANCE || 'daily_attendance').trim();
const COLLECTION_TIPOS_INCIDENCIA = (process.env.BASE_COLLECTION_TIPOS_INCIDENCIA || 'tipo_incidencias').trim();
const COLLECTION_INCIDENCIAS = (process.env.BASE_COLLECTION_INCIDENCIAS || 'incidencias').trim();
const COLLECTION_VACACION_SALDOS = (process.env.BASE_COLLECTION_VACACION_SALDOS || 'vacacion_saldos').trim();
const COLLECTION_PAYROLL_CONCEPTS = (process.env.BASE_COLLECTION_PAYROLL_CONCEPTS || 'payroll_concepts').trim();
const COLLECTION_PAYROLL_PERIODS = (process.env.BASE_COLLECTION_PAYROLL_PERIODS || 'payroll_periods').trim();
const COLLECTION_PAYROLL_DETAILS = (process.env.BASE_COLLECTION_PAYROLL_DETAILS || 'payroll_details').trim();
const COLLECTION_INTEGRATION_PROFILES = (process.env.BASE_COLLECTION_INTEGRATION_PROFILES || 'integration_profiles').trim();
const COLLECTION_SYNC_LOGS = (process.env.BASE_COLLECTION_SYNC_LOGS || 'sync_logs').trim();
const COLLECTION_BIOMETRIC_DEVICES = (process.env.BASE_COLLECTION_BIOMETRIC_DEVICES || 'biometric_devices').trim();
const COLLECTION_GRUPOS_DISPOSITIVOS = (process.env.BASE_COLLECTION_GRUPOS_DISPOSITIVOS || 'grupos_dispositivos').trim();
const COLLECTION_PLANTILLAS_ROTACION = (process.env.BASE_COLLECTION_PLANTILLAS_ROTACION || 'plantillas_rotacion').trim();
const COLLECTION_ASIGNACIONES_ROTACION = (process.env.BASE_COLLECTION_ASIGNACIONES_ROTACION || 'asignaciones_rotacion').trim();
const COLLECTION_OVERRIDES_TURNO = (process.env.BASE_COLLECTION_OVERRIDES_TURNO || 'overrides_turno').trim();
const COLLECTION_NOMINA_CONCEPTOS = (process.env.BASE_COLLECTION_NOMINA_CONCEPTOS || 'nomina_conceptos').trim();
const COLLECTION_NOMINA_FORMULAS = (process.env.BASE_COLLECTION_NOMINA_FORMULAS || 'nomina_formulas').trim();
const COLLECTION_NOMINA_PERIODOS = (process.env.BASE_COLLECTION_NOMINA_PERIODOS || 'nomina_periods').trim();
const COLLECTION_NOMINA_RECIBOS = (process.env.BASE_COLLECTION_NOMINA_RECIBOS || 'nomina_recibos').trim();
const COLLECTION_NOMINA_APLICADOS = (process.env.BASE_COLLECTION_NOMINA_APLICADOS || 'nomina_conceptos_aplicados').trim();
const COLLECTION_NOMINA_CALCULO_JOBS = (process.env.BASE_COLLECTION_NOMINA_CALCULO_JOBS || 'nomina_calculo_jobs').trim();
const COLLECTION_TABLAS_FISCALES = (process.env.BASE_COLLECTION_TABLAS_FISCALES || 'tablas_fiscales').trim();
const COLLECTION_RANGOS_FISCALES = (process.env.BASE_COLLECTION_RANGOS_FISCALES || 'rangos_fiscales').trim();
const COLLECTION_PARAMETROS_GENERALES = (process.env.BASE_COLLECTION_PARAMETROS_GENERALES || 'parametros_generales').trim();
const COLLECTION_CATALOGOS_SAT = (process.env.BASE_COLLECTION_CATALOGOS_SAT || 'catalogos_sat').trim();
const COLLECTION_CATALOGO_MAPEO_LEGADO =
  (process.env.BASE_COLLECTION_CATALOGO_MAPEO_LEGADO || 'nomina_catalogo_mapeo_legado').trim();
const COLLECTION_TIPOS_MOVIMIENTO_LABORAL =
  (process.env.BASE_COLLECTION_TIPOS_MOVIMIENTO_LABORAL || 'tipos_movimiento_laboral').trim();
const COLLECTION_HISTORIAL_LABORAL =
  (process.env.BASE_COLLECTION_HISTORIAL_LABORAL || 'historial_laboral').trim();
const COLLECTION_MOVIMIENTOS_ASISTENCIA_NOMINA =
  (process.env.BASE_COLLECTION_MOVIMIENTOS_ASISTENCIA_NOMINA || 'movimientos_asistencia_nomina').trim();
const COLLECTION_TIPOS_PERIODO_NOMINA =
  (process.env.BASE_COLLECTION_TIPOS_PERIODO_NOMINA || 'tipos_periodo_nomina').trim();
const COLLECTION_CENTROS_COSTO =
  (process.env.BASE_COLLECTION_CENTROS_COSTO || 'centros_costo').trim();
const COLLECTION_CONCEPT_CATALOG =
  (process.env.BASE_COLLECTION_CONCEPT_CATALOG || 'concept_catalog').trim();
const COLLECTION_COMPANY_CONCEPT_CONFIG =
  (process.env.BASE_COLLECTION_COMPANY_CONCEPT_CONFIG || 'company_concept_config').trim();
const COLLECTION_SYSTEM_ENUMS =
  (process.env.BASE_COLLECTION_SYSTEM_ENUMS || 'system_enums').trim();
const COLLECTION_AYUDA_ARTICULOS =
  (process.env.BASE_COLLECTION_AYUDA_ARTICULOS || 'ayuda_articulos').trim();
const COLLECTION_NOMINA_HISTORICO =
  (process.env.BASE_COLLECTION_NOMINA_HISTORICO || 'nomina_historico_recibos').trim();
const COLLECTION_NOMINA_ACUMULADOS =
  (process.env.BASE_COLLECTION_NOMINA_ACUMULADOS || 'nomina_acumulados').trim();
const COLLECTION_NOMINA_AUDITORIA =
  (process.env.BASE_COLLECTION_NOMINA_AUDITORIA || 'nomina_auditoria').trim();
const COLLECTION_CARGAS_INICIALES =
  (process.env.BASE_COLLECTION_CARGAS_INICIALES || 'cargas_iniciales_jobs').trim();
const COLLECTION_TABLAS_PRESTACIONES =
  (process.env.BASE_COLLECTION_TABLAS_PRESTACIONES || 'tablas_prestaciones').trim();
const COLLECTION_FORMULA_FUNCTIONS =
  (process.env.BASE_COLLECTION_FORMULA_FUNCTIONS || 'nomina_formula_functions').trim();
const COLLECTION_LAYOUTS_BANCARIOS =
  (process.env.BASE_COLLECTION_LAYOUTS_BANCARIOS || 'layouts_bancarios').trim();
const COLLECTION_PAC_CONFIGS =
  (process.env.BASE_COLLECTION_PAC_CONFIGS || 'pac_configs').trim();
const COLLECTION_RECIBO_PDF_PLANTILLAS =
  (process.env.BASE_COLLECTION_RECIBO_PDF_PLANTILLAS || 'recibo_pdf_plantillas').trim();
const COLLECTION_TIMBRADO_LOTES =
  (process.env.BASE_COLLECTION_TIMBRADO_LOTES || 'timbrado_lotes').trim();
const COLLECTION_NOMINA_CFDI_ARCHIVOS =
  (process.env.BASE_COLLECTION_NOMINA_CFDI_ARCHIVOS || 'nomina_cfdi_archivos').trim();
const COLLECTION_ASISTENCIA_AUDITORIA =
  (process.env.BASE_COLLECTION_ASISTENCIA_AUDITORIA || 'asistencia_auditoria').trim();
const COLLECTION_AJUSTE_ANUAL_LOTES =
  (process.env.BASE_COLLECTION_AJUSTE_ANUAL_LOTES || 'ajuste_anual_lotes').trim();
const COLLECTION_CORREO_CONFIGS =
  (process.env.BASE_COLLECTION_CORREO_CONFIGS || 'correo_configs').trim();
const COLLECTION_GESTION_DOCUMENTAL_CONFIG =
  (process.env.BASE_COLLECTION_GESTION_DOCUMENTAL_CONFIG || 'gestion_documental_config').trim();
const COLLECTION_DOCUMENTOS_ARCHIVO =
  (process.env.BASE_COLLECTION_DOCUMENTOS_ARCHIVO || 'documentos_archivo').trim();
const COLLECTION_FINIQUITO_CALCULOS =
  (process.env.BASE_COLLECTION_FINIQUITO_CALCULOS || 'finiquito_calculos').trim();
const COLLECTION_PUNTOS_ACCESO =
  (process.env.BASE_COLLECTION_PUNTOS_ACCESO || 'puntos_acceso').trim();
const COLLECTION_ASIGNACIONES_PUNTO_ACCESO =
  (process.env.BASE_COLLECTION_ASIGNACIONES_PUNTO_ACCESO || 'asignaciones_punto_acceso').trim();

module.exports = {
  COLLECTION_ROLES,
  COLLECTION_USERS,
  COLLECTION_DEPARTAMENTOS,
  COLLECTION_PUESTOS,
  COLLECTION_EMPLEADOS,
  COLLECTION_TURNOS,
  COLLECTION_ATTENDANCE_RECORDS,
  COLLECTION_DAILY_ATTENDANCE,
  COLLECTION_TIPOS_INCIDENCIA,
  COLLECTION_INCIDENCIAS,
  COLLECTION_VACACION_SALDOS,
  COLLECTION_PAYROLL_CONCEPTS,
  COLLECTION_PAYROLL_PERIODS,
  COLLECTION_PAYROLL_DETAILS,
  COLLECTION_INTEGRATION_PROFILES,
  COLLECTION_SYNC_LOGS,
  COLLECTION_BIOMETRIC_DEVICES,
  COLLECTION_GRUPOS_DISPOSITIVOS,
  COLLECTION_PLANTILLAS_ROTACION,
  COLLECTION_ASIGNACIONES_ROTACION,
  COLLECTION_OVERRIDES_TURNO,
  COLLECTION_NOMINA_CONCEPTOS,
  COLLECTION_NOMINA_FORMULAS,
  COLLECTION_NOMINA_PERIODOS,
  COLLECTION_NOMINA_RECIBOS,
  COLLECTION_NOMINA_APLICADOS,
  COLLECTION_NOMINA_CALCULO_JOBS,
  COLLECTION_TABLAS_FISCALES,
  COLLECTION_RANGOS_FISCALES,
  COLLECTION_PARAMETROS_GENERALES,
  COLLECTION_CATALOGOS_SAT,
  COLLECTION_CATALOGO_MAPEO_LEGADO,
  COLLECTION_TIPOS_MOVIMIENTO_LABORAL,
  COLLECTION_HISTORIAL_LABORAL,
  COLLECTION_MOVIMIENTOS_ASISTENCIA_NOMINA,
  COLLECTION_TIPOS_PERIODO_NOMINA,
  COLLECTION_CENTROS_COSTO,
  COLLECTION_CONCEPT_CATALOG,
  COLLECTION_COMPANY_CONCEPT_CONFIG,
  COLLECTION_SYSTEM_ENUMS,
  COLLECTION_AYUDA_ARTICULOS,
  COLLECTION_NOMINA_HISTORICO,
  COLLECTION_NOMINA_ACUMULADOS,
  COLLECTION_NOMINA_AUDITORIA,
  COLLECTION_CARGAS_INICIALES,
  COLLECTION_TABLAS_PRESTACIONES,
  COLLECTION_FORMULA_FUNCTIONS,
  COLLECTION_LAYOUTS_BANCARIOS,
  COLLECTION_PAC_CONFIGS,
  COLLECTION_RECIBO_PDF_PLANTILLAS,
  COLLECTION_TIMBRADO_LOTES,
  COLLECTION_NOMINA_CFDI_ARCHIVOS,
  COLLECTION_ASISTENCIA_AUDITORIA,
  COLLECTION_AJUSTE_ANUAL_LOTES,
  COLLECTION_CORREO_CONFIGS,
  COLLECTION_GESTION_DOCUMENTAL_CONFIG,
  COLLECTION_DOCUMENTOS_ARCHIVO,
  COLLECTION_FINIQUITO_CALCULOS,
  COLLECTION_PUNTOS_ACCESO,
  COLLECTION_ASIGNACIONES_PUNTO_ACCESO
};
