server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Cache estáticos con revalidación suave en dev
    location ~* \.(css|js|png|jpg|jpeg|gif|ico|svg|woff2?)$ {
        expires 1h;
        add_header Cache-Control "public";
        try_files $uri =404;
    }

    # Descargas de apps (APK/EXE/DMG/IPA)
    location /downloads/ {
        autoindex off;
        add_header Content-Disposition 'attachment';
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ $uri.html /index.html;
    }

    # Evitar listar directorios
    location = /downloads {
        return 302 /downloads/;
    }
}
